server.port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db
    username: root
    password: Password@123
    ## Hibernate properties
  jpa:
    hibernate.ddl-auto: none
    open-in-view: false
  flyway:
    url: jdbc:mysql://localhost:3306/auth_db
    enabled: true
    schemas: auth_db
    user: root
    password: Password@123

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
  # 1h in millisecond
    expiration-time: 3600000

