server.port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db
    username: root
    password: 12345
    ## Hibernate properties
  jpa:
    hibernate.ddl-auto: update
    open-in-view: false