CREATE TABLE IF NOT EXISTS user (
  id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  full_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  created_at VARCHAR(255) NOT NULL,
  updated_at VARCHAR(255) NOT NULL
);

CREATE UNIQUE INDEX `user_email_index` on user (`email`);